name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 'stable'

      - name: Build Project
        run: |
          ./ghm.sh -build -clean
          ./xp.sh -build

      - name: Create Release and Upload
        uses: softprops/action-gh-release@v3
        with:
          files: |
            build/**/*
          generate_release_notes: true
          prerelease: ${{ contains(github.ref, '-rc') || contains(github.ref, '-beta') }}
